### PR TITLE
Blacklist braddr

### PR DESCRIPTION
**Pull request by wilzbach**
@braddr seems to have touched literally every file in DMD and Phobos and thus be included in most pings.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Should we use a `.mention-bot` file instead?

**Comment by wilzbach** [comment]
> Should we use a .mention-bot file instead?

The .mention-bot is per repository, so it allows further customization, which I think we don't need for now?

**Comment by wilzbach** [comment]
> The .mention-bot is per repository, so it allows further customization, which I think we don't need for now?

I was trying to say that for now we are better off of we don't need to merge files into the official repositories.

**Comment by braddr** [comment]
Certainly a quick way of handling this, but really, probably not the best.  There should likely be a time based element to who's mentioned.

**Comment by wilzbach** [comment]
> Certainly a quick way of handling this, but really, probably not the best. There should likely be a time based element to who's mentioned.

@braddr at the moment we are just experimenting whether pinging based on the diff is helpful. If it turns out to do so, we will do it properly in D, but for now just toggling some options in the Javascript tool is faster.

**Comment by MartinNowak** [comment]
> Certainly a quick way of handling this, but really, probably not the best. There should likely be a time based element to who's mentioned.

Yes, it's already obvious that this is a problem with mention-bot.

**Comment by vjeux** [comment]
FYI, we implemented a time based to mention-bot for all fb projects (implemented in Hack) and it gave dramatically better results for people that used to work on the codebase but moved on to other projects.

The formula is really simple: for each line of code that is blamed, instead of adding 1, add a linear interpolation where now is 360 and 8 months in the past (or more) is 0.

I'd love to make that the default on the open source mention-bot project (in JavaScript), if you fancy implementing it and sending a pull request over there, I would appreciate :)

cc @mkonicek

**Pull request merged**
